### ISSUE TITLE
Unable to install theme dependencies

### ISSUE THREAD

**Issue by MurhafSousli** [pascallaliberte/built-with-roots#8]
Hi @pascallaliberte, thanks for the tutorial
I followed your instruction until I reached installing theme dependencies

![image](https://cloud.githubusercontent.com/assets/8130692/26811523/1efa25fe-4a7b-11e7-81ec-067cbf451668.png)

As you can see in the screenshot

Both commands are not installing any dependencies:
 - `composer install` gives nothing to install
 - `yarn install` no such file or directory

***

I have also noticed that I got different 'require' in `composer.json` from the one shown in your video

![image](https://cloud.githubusercontent.com/assets/8130692/26811671/edf23090-4a7b-11e7-9729-369575e1a996.png)

The one I got 

```
"require": {
    "php": ">=5.6.4",
    "composer/installers": "~1.0",
    "illuminate/view": "~5.4.0",
    "illuminate/config": "~5.4.0"
  },
```

Am I doing something wrong? 

regards.

**Comment by MurhafSousli** [comment]
Okay, now I got it, you have added those packages in  `composer.json` which they were not there by default.
For yarn I had to install it with npm first `npm install -g yarnpkg` (which I thought I did)

**Comment by pascallaliberte** [comment]
@MurhafSousli: the thing about `composer.json` is that there are two of them, serving two purposes:

* `site/composer.json` sets up wordpress itself (`johnpbloch/wordpress`) and other core dependencies for running Bedrock. Run `composer install` from the `site/` directory.
* `site/web/app/themes/built-with-roots/composer.json` is the Sage theme's php dependencies, which, mainly, make it render blade templates down into wordpress templates (and cache them). Run `composer install` from the theme's directory.

Also: good catch about needing to install yarn.
