### ISSUE TITLE
site is not opening after `vargant up`

### ISSUE THREAD

**Issue by MurhafSousli** [pascallaliberte/built-with-roots#9]
I am using Ubuntu,
I reached **step 4** where I run `vargant up`

![image](https://cloud.githubusercontent.com/assets/8130692/26813522/7e6aaf8e-4a87-11e7-838f-9707ed228985.png)

It seems to be working, but in **step 5**:

when I go to `http://shop-theme.dev` (in my case), it does not open!
I also tried `http://example.dev`, the browser's spinner keep spinning but the page does not open!

Any idea?

**Comment by pascallaliberte** [comment]
Here's a checklist of the places where `shop-theme.dev` will have to be set (replacing `built-with-roots.dev` in this example repo):

* `trellis/group_vars/development/wordpress_sites.yml`
* `site/web/app/themes/built-with-roots/resources/assets/config.json`

If that was it, and you changed what's in the trellis configs, just run `vagrant reload --provision`.

Another thing to check for (first): in your `/etc/hosts` file, does it have any entries added by vagrant?

**Comment by MurhafSousli** [comment]
Thank you
